FROM docker.io/opensuse/tumbleweed:latest

#RUN zypper ar -p 95 -f https://download.opensuse.org/repositories/devel:/openQA/openSUSE_Tumbleweed devel_openQA && \
#    zypper --gpg-auto-import-keys ref && \
#    zypper in -y openQA-client git && \
#    zypper clean
