FROM docker.io/opensuse/leap:15.5

#RUN zypper ar -p 95 -f https://download.opensuse.org/repositories/devel:/openQA/openSUSE_Tumbleweed devel_openQA && \
#    zypper --gpg-auto-import-keys ref && \
#    zypper in -y openQA-client git && \
#    zypper clean
