name: linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]


jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
        - '5.20'
        - '5.22'
        - '5.24'
        - '5.26'
        - '5.28'
        - '5.30'
        - '5.32'
        - '5.34'
        - '5.36'
        - '5.38'
    container:
      image: perl:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v3
    - run: perl -V
    - run: env | sort
    - name: Install deps
      run: >
        cpanm --notest
        YAML::PP YAML::LibYAML::API@0.013 Getopt::Long::Descriptive
        Test::Deep Test::Warnings Test::More JSON::PP


    - name: Run Tests
      run: |
        make -f Makefile.dev yts
        prove -lr t


  authortests:
    runs-on: ubuntu-latest

    container:
      image: perl:5.32

    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - run: perl -V
    - name: Install deps
      run: >
        apt-get update && apt-get install -y aspell

        cpanm --notest Test::Spelling Test::Pod
    - name: Run Tests
      run: prove -lv xt/03.spelling.t xt/04.pod.t

  testtest:
    runs-on: ubuntu-latest

    steps:
    - run: exit 1
      continue-on-error: true
    - run: echo "Still alive!"
